/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#define RCC_Base 0x40021000
#define GPIO_Base 0x40010800
#define RCC_APB2ENR *(volatile unsigned int*)(RCC_Base+0x18)
#define GPIO_CRH *(volatile unsigned int*)(GPIO_Base+0x04)
#define GPIO_ODR *(volatile unsigned int*)(GPIO_Base+0x0c)
typedef union {
	unsigned int all_pins;
	struct {
	unsigned int reserved:13;
	unsigned int P13:1;
	} pin;
}R_ODR_t;
volatile R_ODR_t* R_ODR =(volatile R_ODR_t*) (GPIO_Base+0x0c);

#include"stdio.h"
int main()
{
	RCC_APB2ENR|=(1>>2);
	GPIO_CRH &= 0xFF0FFFFF;
	GPIO_CRH |= 0x00200000;
	while(1)
	{
		R_ODR->pin.P13 =0;
		for(int i=0 ; i<5 ; i++)
		{
			R_ODR->pin.P13=1;
		}
		for(int i=0 ; i<5 ; i++)
		{

		}
	}
	return 0;
}


